Add `clang-format` check

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -114,10 +114,33 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Install dependencies
+      run: |
+        sudo apt update
+        sudo apt -q install clang-format
     - name: Check out code
       uses: actions/checkout@v4
-
+    - name: Check formatting
+      if: '!cancelled()'
+      run: |
+        make -C src format
+        git diff > formatting-fixes.diff
+        if ! grep "" formatting-fixes.diff; then
+          rm -f formatting-fixes.diff
+        else
+          (echo "Formatting errors detected by clang-format. Please run" \
+                "\`make format\` or apply formatting-fixes.diff below.";
+           echo) >> $GITHUB_STEP_SUMMARY
+          false
+        fi
+    - uses: actions/upload-artifact@v4
+      if: '!cancelled()'
+      with:
+        if-no-files-found: ignore
+        name: formatting-fixes.diff
+        path: formatting-fixes.diff
     - name: Check for banned functions (should use checked_*)
+      if: '!cancelled()'
       run: |
         success=true
         for func in malloc realloc calloc strdup \
@@ -126,4 +149,9 @@ jobs:
             success=false
           fi
         done
-        $success
+        if ! $success; then
+          (echo "Use of banned functions detected. Please replace with the" \
+                "checked_* versions of these functions.";
+           echo) >> $GITHUB_STEP_SUMMARY
+          false
+        fi
